### PR TITLE
Add CRUD operations for movie objects

### LINKED ISSUE #5: Add movieUtilities.js (CRUD for Browser Local Storage)

### PR DESCRIPTION
**Pull request by mfletcher2**
Adds movieUtils.js for CRUD operations on movies.
Depends on #6, so we should probably wait until that is merged first because the tests fail.

Closes #5

### CODE REVIEW

**Comment by TheRealJBomb** [comment]
@GlassBricks and @mfletcher2 how can we get rid of the 22 changed files and for this PR only have the files changed pertaining to CRUD operations for movie objects? The other changed files are already in main.

**Comment by mfletcher2** [comment]
well that didn't work

**Comment by mfletcher2** [comment]
I got it. I reverted to the proper commit and then force pushed it to Github.

**Comment by GlassBricks** [comment]
LGTM

**Pull request merged**
